// These styles apply to every route in the application
import AppContext from "../context/UserContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppContext>{children} </AppContext>
      </body>
    </html>
  );
}
